INSERT INTO favorites(user_id, fid) VALUES
	('BigBird@sesameStreet.com', 1),
	('BigBird@sesameStreet.com', 3),
	('BigBird@sesameStreet.com', 4), 
	('TomDodge@gmail.com', 20),
	('TomDodge@gmail.com', 40),
	('TomDodge@gmail.com', 80), 
	('vincentAdultman@corporatePlace.com', 7),
	('vincentAdultman@corporatePlace.com', 13),
	('vincentAdultman@corporatePlace.com', 64),
    ('grayman98@gmail.com', 13),
    ('grayman98@gmail.com', 50),
    ('grayman98@gmail.com', 78),
    ('newunusedname@gmail.com', 13),
    ('newunusedname@gmail.com', 64),
    ('newunusedname@gmail.com', 38),
    ('graysoncox98@gmail.com', 12),
    ('graysoncox98@gmail.com', 64);